### ISSUE TITLE
Funcionalidade de Filtros

### ISSUE THREAD

**Issue by gabrielligoski** [gabrielligoski/CAMAAR#3]
## Pesquisa
- [x] Componente de pesquisa
## Professor
- [ ] Filtrar por Professor.
## Matéria
- [x] Filtrar por Matéria.

## Turma
- [x] Filtrar por turma.

#### Semestre
- [ ] Filtrar por semestre dentro de turma.
