### ISSUE TITLE
Tela de relatórios

### ISSUE THREAD

**Issue by gabrielligoski** [gabrielligoski/CAMAAR#4]
## Lista de disciplinas
- [x] Componente Lista de disciplinas
## Dropdown da disciplina
- [x] Componente  de dropdown da disciplina
## Visualização da turma
- [x] Componente da turma
